"""Generates a PDF compliance report for a scanned product."""
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

REPORTS_DIR = Path(__file__).parent.parent.parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)


def generate_pdf_report(product_id: int, product_name: str, overall_status: str, violations: list) -> str:
    output_path = REPORTS_DIR / f"compliance_report_{product_id}.pdf"
    doc = SimpleDocTemplate(str(output_path), pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Legal Metrology Compliance Report", styles["Title"]))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(f"Product: {product_name or 'Unknown'}", styles["Normal"]))
    elements.append(Paragraph(f"Scan ID: {product_id}", styles["Normal"]))

    status_color = colors.red if overall_status == "FAIL" else colors.green
    status_style = styles["Heading2"]
    status_style.textColor = status_color
    elements.append(Paragraph(f"Overall Status: {overall_status}", status_style))
    elements.append(Spacer(1, 16))

    if violations:
        elements.append(Paragraph("Violations Detected", styles["Heading3"]))
        data = [["Rule", "Declaration", "Status", "Detail", "Confidence"]]
        for v in violations:
            data.append([
                v.rule_code if hasattr(v, "rule_code") else v["rule_code"],
                v.declaration if hasattr(v, "declaration") else v["declaration"],
                v.status if hasattr(v, "status") else v["status"],
                (v.detail if hasattr(v, "detail") else v["detail"])[:60],
                f"{(v.confidence if hasattr(v, 'confidence') else v['confidence']):.0%}",
            ])
        table = Table(data, colWidths=[80, 120, 70, 180, 60])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(table)
    else:
        elements.append(Paragraph("No violations detected — all checked declarations present and valid.", styles["Normal"]))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "Generated by SIH26034 Compliance Checker. Automated result — for enforcement "
        "action, verify flagged items against the physical product before proceeding.",
        styles["Italic"],
    ))

    doc.build(elements)
    return str(output_path)
